package io.cassiopee.textbook.entities.enums;

public enum TypePrivilege {
    ACCESS_TO_ADMIN,
    ADD_ADMINISTRATION,

    ACCESS_ADMINISTRATION,
    ADD_ACTOR_ON_DASH,
    CREATE_ACTOR,
    READ_ACTOR,
    UPDATE_ACTOR,
    DELETE_ACTOR,
    CREATE_SUBJECT,
    READ_SUBJECT,
    UPDATE_SUBJECT,
    DELETE_SUBJECT,
    CREATE_OPTION,
    READ_OPTION,
    UPDATE_OPTION,
    DELETE_OPTION,
    CREATE_FIELD,
    READ_FIELD,
    UPDATE_FIELD,
    DELETE_FIELD,

    ACCESS_HEAD_DEPARTMENT,
    ADD_TEACHER,
    PROGRAM_COURSE,
    VALIDATE_PROGRAMING,
    ADD_HEADER_OF_CLASS,

    ACCESS_TEACHER,
    FILL_BOOK_NOTE,
    VALIDATE_DONE_COURSE,

    ACCESS_HEAD_CLASS,
    FILL_BOOK


}
